### ISSUE TITLE
Logo for React Machinery

### ISSUE THREAD

**Issue by francisrstokes** [francisrstokes/React-Machinery#2]

**Comment by ayushs08** [comment]
Hi,

How do you feel about something like this?

Okay so I can't out svg here...Here's a zip file

[react-machinery-logo.zip](https://github.com/francisrstokes/React-Machinery/files/2309067/react-machinery-logo.zip)

**Comment by francisrstokes** [comment]
Hi @ayushs08 

This is great! I love it.


Would you be happy to release this under a Creative Commons by Attribution license (https://creativecommons.org/licenses/by/3.0/)?

**Comment by ayushs08** [comment]
@francisrstokes go ahead man. Happy to help!

**Comment by francisrstokes** [comment]
Amazing! Thank you - I've placed the logo in the readme along with a credit.
