### ISSUE TITLE
Empty State Error

### ISSUE THREAD

**Issue by geoquant** [francisrstokes/React-Machinery#5]
<img width="728" alt="Screen Shot 2019-05-14 at 10 32 15 AM" src="https://user-images.githubusercontent.com/1237781/57719113-de824600-7633-11e9-9ea7-0726fed9bc11.png">

xhr.js?b50d:178 GET http://localhost:8080/api/2.0/profile/dom.testci260420161a200c/picture 404 (Not Found)
dispatchXhrRequest @ xhr.js?b50d:178
xhrAdapter @ xhr.js?b50d:12
dispatchRequest @ dispatchRequest.js?5270:59
Promise.then (async)
request @ Axios.js?0a06:51
wrap @ bind.js?1d2b:9
get @ BaseAPI.js?0d25:111
profile_get_picture @ profileAction.js?01ad:19
init @ profileAction.js?01ad:15
componentDidMount @ Application.js?5f0f:45
componentDidMount @ react-hot-loader.development.js?c2cb:651
commitLifeCycles @ react-dom.development.js?7f13:17335
commitAllLifeCycles @ react-dom.development.js?7f13:18737
callCallback @ react-dom.development.js?7f13:150
invokeGuardedCallbackDev @ react-dom.development.js?7f13:200
invokeGuardedCallback @ react-dom.development.js?7f13:257
commitRoot @ react-dom.development.js?7f13:18949
(anonymous) @ react-dom.development.js?7f13:20419
unstable_runWithPriority @ scheduler.development.js?3069:255
completeRoot @ react-dom.development.js?7f13:20418
performWorkOnRoot @ react-dom.development.js?7f13:20347
performWork @ react-dom.development.js?7f13:20255
performSyncWork @ react-dom.development.js?7f13:20229
requestWork @ react-dom.development.js?7f13:20098
scheduleWork @ react-dom.development.js?7f13:19912
scheduleRootUpdate @ react-dom.development.js?7f13:20573
updateContainerAtExpirationTime @ react-dom.development.js?7f13:20601
updateContainer @ react-dom.development.js?7f13:20658
ReactRoot.render @ react-dom.development.js?7f13:20954
(anonymous) @ react-dom.development.js?7f13:21091
unbatchedUpdates @ react-dom.development.js?7f13:20460
legacyRenderSubtreeIntoContainer @ react-dom.development.js?7f13:21087
render @ react-dom.development.js?7f13:21199
(anonymous) @ main.js?2ee2:20
reactHotReload @ main.js?2ee2:19
_callee$ @ main.js?2ee2:85
tryCatch @ runtime.js?96cf:62
invoke @ runtime.js?96cf:296
prototype.<computed> @ runtime.js?96cf:114
step @ main.js:26
(anonymous) @ main.js:26
Promise.then (async)
step @ main.js:26
(anonymous) @ main.js:26
(anonymous) @ main.js:26
j @ jquery-3.2.1.min.js:2
k @ jquery-3.2.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.1.min.js:2
i @ jquery-3.2.1.min.js:2
fireWith @ jquery-3.2.1.min.js:2
fire @ jquery-3.2.1.min.js:2
i @ jquery-3.2.1.min.js:2
fireWith @ jquery-3.2.1.min.js:2
ready @ jquery-3.2.1.min.js:2
S @ jquery-3.2.1.min.js:3
Show 10 more frames
index.js?f549:76 Uncaught Error: Tried to transition from state '<no state>' to 'undefined'. Valid states are: [wait-for-input, verification-pending]
    at StateMachine.transition (index.js?f549:76)
    at StateMachine.transition (react-hot-loader.development.js?c2cb:661)
    at new StateMachine (index.js?f549:58)
    at new StateMachine (eval at ES6ProxyComponentFactory (react-hot-loader.development.js?c2cb:2719), <anonymous>:5:7)
    at constructClassInstance (react-dom.development.js?7f13:11362)
    at updateClassComponent (react-dom.development.js?7f13:14688)
    at beginWork (react-dom.development.js?7f13:15645)
    at performUnitOfWork (react-dom.development.js?7f13:19313)
    at workLoop (react-dom.development.js?7f13:19353)
    at HTMLUnknownElement.callCallback (react-dom.development.js?7f13:150)
transition @ index.js?f549:76
getDomainPrivacyCost @ react-hot-loader.development.js?c2cb:661
StateMachine @ index.js?f549:58
StateMachine @ VM6357:5
constructClassInstance @ react-dom.development.js?7f13:11362
updateClassComponent @ react-dom.development.js?7f13:14688
beginWork @ react-dom.development.js?7f13:15645
performUnitOfWork @ react-dom.development.js?7f13:19313
workLoop @ react-dom.development.js?7f13:19353
callCallback @ react-dom.development.js?7f13:150
invokeGuardedCallbackDev @ react-dom.development.js?7f13:200
invokeGuardedCallback @ react-dom.development.js?7f13:257
replayUnitOfWork @ react-dom.development.js?7f13:18579
renderRoot @ react-dom.development.js?7f13:19469
performWorkOnRoot @ react-dom.development.js?7f13:20343
performWork @ react-dom.development.js?7f13:20255
performSyncWork @ react-dom.development.js?7f13:20229
requestWork @ react-dom.development.js?7f13:20098
scheduleWork @ react-dom.development.js?7f13:19912
enqueueSetState @ react-dom.development.js?7f13:11170
Component.setState @ react.development.js?72d0:335
Domain._this.setSummaryInfo @ Domain.js?a763:196
emit @ index.js?c9fc:94
_this.catch @ domainStore.js?00a0:77
_invokeCallback @ Dispatcher.js?4644:198
dispatch @ Dispatcher.js?4644:174
(anonymous) @ domainAction.js?f97d:122
(anonymous) @ BaseAPI.js?0d25:41
Promise.then (async)
get @ BaseAPI.js?0d25:111
get_domain_contact_info @ domainAction.js?f97d:121
componentWillMount @ Domain.js?a763:118
callComponentWillMount @ react-dom.development.js?7f13:11422
mountClassInstance @ react-dom.development.js?7f13:11515
updateClassComponent @ react-dom.development.js?7f13:14689
beginWork @ react-dom.development.js?7f13:15645
performUnitOfWork @ react-dom.development.js?7f13:19313
workLoop @ react-dom.development.js?7f13:19353
renderRoot @ react-dom.development.js?7f13:19436
performWorkOnRoot @ react-dom.development.js?7f13:20343
performWork @ react-dom.development.js?7f13:20255
performSyncWork @ react-dom.development.js?7f13:20229
interactiveUpdates$1 @ react-dom.development.js?7f13:20496
interactiveUpdates @ react-dom.development.js?7f13:2171
dispatchInteractiveEvent @ react-dom.development.js?7f13:4883
react-dom.development.js?7f13:17118 The above error occurred in the <StateMachine> component:
    in StateMachine (created by Domain)
    in div (created by Domain)
    in div (created by Domain)
    in div (created by Domain)
    in Domain (created by Route)
    in Route (created by DomainRouter)
    in Switch (created by DomainRouter)
    in div (created by DomainRouter)
    in DomainRouter (created by Route)
    in Route (created by Application)
    in Switch (created by Application)
    in div (created by Application)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by Application)
    in Application
    in AppContainer

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
logCapturedError @ react-dom.development.js?7f13:17118
logError @ react-dom.development.js?7f13:17154
callback @ react-dom.development.js?7f13:18095
callCallback @ react-dom.development.js?7f13:16434
commitUpdateEffects @ react-dom.development.js?7f13:16473
commitUpdateQueue @ react-dom.development.js?7f13:16464
commitLifeCycles @ react-dom.development.js?7f13:17365
commitAllLifeCycles @ react-dom.development.js?7f13:18737
callCallback @ react-dom.development.js?7f13:150
invokeGuardedCallbackDev @ react-dom.development.js?7f13:200
invokeGuardedCallback @ react-dom.development.js?7f13:257
commitRoot @ react-dom.development.js?7f13:18949
(anonymous) @ react-dom.development.js?7f13:20419
unstable_runWithPriority @ scheduler.development.js?3069:255
completeRoot @ react-dom.development.js?7f13:20418
performWorkOnRoot @ react-dom.development.js?7f13:20347
performWork @ react-dom.development.js?7f13:20255
performSyncWork @ react-dom.development.js?7f13:20229
requestWork @ react-dom.development.js?7f13:20098
scheduleWork @ react-dom.development.js?7f13:19912
enqueueSetState @ react-dom.development.js?7f13:11170
Component.setState @ react.development.js?72d0:335
Domain._this.setSummaryInfo @ Domain.js?a763:196
emit @ index.js?c9fc:94
_this.catch @ domainStore.js?00a0:77
_invokeCallback @ Dispatcher.js?4644:198
dispatch @ Dispatcher.js?4644:174
(anonymous) @ domainAction.js?f97d:122
(anonymous) @ BaseAPI.js?0d25:41
Promise.then (async)
get @ BaseAPI.js?0d25:111
get_domain_contact_info @ domainAction.js?f97d:121
componentWillMount @ Domain.js?a763:118
callComponentWillMount @ react-dom.development.js?7f13:11422
mountClassInstance @ react-dom.development.js?7f13:11515
updateClassComponent @ react-dom.development.js?7f13:14689
beginWork @ react-dom.development.js?7f13:15645
performUnitOfWork @ react-dom.development.js?7f13:19313
workLoop @ react-dom.development.js?7f13:19353
renderRoot @ react-dom.development.js?7f13:19436
performWorkOnRoot @ react-dom.development.js?7f13:20343
performWork @ react-dom.development.js?7f13:20255
performSyncWork @ react-dom.development.js?7f13:20229
interactiveUpdates$1 @ react-dom.development.js?7f13:20496
interactiveUpdates @ react-dom.development.js?7f13:2171
dispatchInteractiveEvent @ react-dom.development.js?7f13:4883
react-hot-loader.development.js?c2cb:241 Error: Tried to transition from state '<no state>' to 'undefined'. Valid states are: [wait-for-input, verification-pending]
    at StateMachine.transition (index.js?f549:76)
    at StateMachine.transition (react-hot-loader.development.js?c2cb:661)
    at new StateMachine (index.js?f549:58)
    at new StateMachine (eval at ES6ProxyComponentFactory (react-hot-loader.development.js?c2cb:2719), <anonymous>:5:7)
    at constructClassInstance (react-dom.development.js?7f13:11362)
    at updateClassComponent (react-dom.development.js?7f13:14688)
    at beginWork (react-dom.development.js?7f13:15645)
    at performUnitOfWork (react-dom.development.js?7f13:19313)
    at workLoop (react-dom.development.js?7f13:19353)
    at renderRoot (react-dom.development.js?7f13:19436)
error @ react-hot-loader.development.js?c2cb:241
componentDidCatch @ react-hot-loader.development.js?c2cb:2150
callback @ react-dom.development.js?7f13:18096
callCallback @ react-dom.development.js?7f13:16434
commitUpdateEffects @ react-dom.development.js?7f13:16473
commitUpdateQueue @ react-dom.development.js?7f13:16464
commitLifeCycles @ react-dom.development.js?7f13:17365
commitAllLifeCycles @ react-dom.development.js?7f13:18737
callCallback @ react-dom.development.js?7f13:150
invokeGuardedCallbackDev @ react-dom.development.js?7f13:200
invokeGuardedCallback @ react-dom.development.js?7f13:257
commitRoot @ react-dom.development.js?7f13:18949
(anonymous) @ react-dom.development.js?7f13:20419
unstable_runWithPriority @ scheduler.development.js?3069:255
completeRoot @ react-dom.development.js?7f13:20418
performWorkOnRoot @ react-dom.development.js?7f13:20347
performWork @ react-dom.development.js?7f13:20255
performSyncWork @ react-dom.development.js?7f13:20229
requestWork @ react-dom.development.js?7f13:20098
scheduleWork @ react-dom.development.js?7f13:19912
enqueueSetState @ react-dom.development.js?7f13:11170
Component.setState @ react.development.js?72d0:335
Domain._this.setSummaryInfo @ Domain.js?a763:196
emit @ index.js?c9fc:94
_this.catch @ domainStore.js?00a0:77
_invokeCallback @ Dispatcher.js?4644:198
dispatch @ Dispatcher.js?4644:174
(anonymous) @ domainAction.js?f97d:122
(anonymous) @ BaseAPI.js?0d25:41
Promise.then (async)
get @ BaseAPI.js?0d25:111
get_domain_contact_info @ domainAction.js?f97d:121
componentWillMount @ Domain.js?a763:118
callComponentWillMount @ react-dom.development.js?7f13:11422
mountClassInstance @ react-dom.development.js?7f13:11515
updateClassComponent @ react-dom.development.js?7f13:14689
beginWork @ react-dom.development.js?7f13:15645
performUnitOfWork @ react-dom.development.js?7f13:19313
workLoop @ react-dom.development.js?7f13:19353
renderRoot @ react-dom.development.js?7f13:19436
performWorkOnRoot @ react-dom.development.js?7f13:20343
performWork @ react-dom.development.js?7f13:20255
performSyncWork @ react-dom.development.js?7f13:20229
interactiveUpdates$1 @ react-dom.development.js?7f13:20496
interactiveUpdates @ react-dom.development.js?7f13:2171
dispatchInteractiveEvent @ react-dom.development.js?7f13:4883
react-hot-loader.development.js?c2cb:2157 Uncaught Error: Tried to transition from state '<no state>' to 'undefined'. Valid states are: [wait-for-input, verification-pending]
    at StateMachine.transition (index.js?f549:76)
    at StateMachine.transition (react-hot-loader.development.js?c2cb:661)
    at new StateMachine (index.js?f549:58)
    at new StateMachine (eval at ES6ProxyComponentFactory (react-hot-loader.development.js?c2cb:2719), <anonymous>:5:7)
    at constructClassInstance (react-dom.development.js?7f13:11362)
    at updateClassComponent (react-dom.development.js?7f13:14688)
    at beginWork (react-dom.development.js?7f13:15645)
    at performUnitOfWork (react-dom.development.js?7f13:19313)
    at workLoop (react-dom.development.js?7f13:19353)
    at renderRoot (react-dom.development.js?7f13:19436)
transition @ index.js?f549:76
getDomainPrivacyCost @ react-hot-loader.development.js?c2cb:661
StateMachine @ index.js?f549:58
StateMachine @ VM6357:5
constructClassInstance @ react-dom.development.js?7f13:11362
updateClassComponent @ react-dom.development.js?7f13:14688
beginWork @ react-dom.development.js?7f13:15645
performUnitOfWork @ react-dom.development.js?7f13:19313
workLoop @ react-dom.development.js?7f13:19353
renderRoot @ react-dom.development.js?7f13:19436
performWorkOnRoot @ react-dom.development.js?7f13:20343
performWork @ react-dom.development.js?7f13:20255
performSyncWork @ react-dom.development.js?7f13:20229
requestWork @ react-dom.development.js?7f13:20098
scheduleWork @ react-dom.development.js?7f13:19912
enqueueSetState @ react-dom.development.js?7f13:11170
Component.setState @ react.development.js?72d0:335
Domain._this.setSummaryInfo @ Domain.js?a763:196
emit @ index.js?c9fc:94
_this.catch @ domainStore.js?00a0:77
_invokeCallback @ Dispatcher.js?4644:198
dispatch @ Dispatcher.js?4644:174
(anonymous) @ domainAction.js?f97d:122
(anonymous) @ BaseAPI.js?0d25:41
Promise.then (async)
get @ BaseAPI.js?0d25:111
get_domain_contact_info @ domainAction.js?f97d:121
componentWillMount @ Domain.js?a763:118
callComponentWillMount @ react-dom.development.js?7f13:11422
mountClassInstance @ react-dom.development.js?7f13:11515
updateClassComponent @ react-dom.development.js?7f13:14689
beginWork @ react-dom.development.js?7f13:15645
performUnitOfWork @ react-dom.development.js?7f13:19313
workLoop @ react-dom.development.js?7f13:19353
renderRoot @ react-dom.development.js?7f13:19436
performWorkOnRoot @ react-dom.development.js?7f13:20343
performWork @ react-dom.development.js?7f13:20255
performSyncWork @ react-dom.development.js?7f13:20229
interactiveUpdates$1 @ react-dom.development.js?7f13:20496
interactiveUpdates @ react-dom.development.js?7f13:2171
dispatchInteractiveEvent @ react-dom.development.js?7f13:4883
react-dom.development.js?7f13:17118 The above error occurred in the <AppContainer> component:
    in AppContainer

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

**Comment by francisrstokes** [comment]
Hi @geoquant 
It's hard to tell exactly whats going on without more information. Apparently your app is trying to enter a new state, but the state name passed is an `undefined` object. Can you share your state machine configuration, along with any code that changes state?
